# https://developers.cloudflare.com/workers/wrangler/configuration

name = "sources"
compatibility_date = "2026-02-06"

compatibility_flags = [
	"nodejs_compat"
]

pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB_Targets"
database_name = "Targets_2026-01-29"
database_id = "a33621b3-fa4a-4399-a7ae-91a012048504"
