# https://developers.cloudflare.com/workers/wrangler/configuration

name = "sources"
compatibility_date = "2026-01-14"

compatibility_flags = [
	"nodejs_compat"
]

pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB_Targets"
database_name = "Targets_2026-01-14"
database_id = "9c2c7c5b-bfe0-48f1-8bb7-c3e17ffc12b3"
